extension=/nix/store/869arapk2wa1vj7yd802wiplwwjim1pw-php-bcmath-8.2.23/lib/php/extensions/bcmath.so
extension=/nix/store/pa11bm3sc4ba64992y8m9fdkfn5grbmf-php-calendar-8.2.23/lib/php/extensions/calendar.so
extension=/nix/store/pm11z4s3vn06va7vnz4x5vjkv7b56h61-php-curl-8.2.23/lib/php/extensions/curl.so
extension=/nix/store/5wmg1qm6n19580ym5rx0kw3vykik7380-php-ctype-8.2.23/lib/php/extensions/ctype.so
extension=/nix/store/mv3xxc9n57ffsdg90ic33shyjrlaichz-php-dom-8.2.23/lib/php/extensions/dom.so
extension=/nix/store/xya9n0p29wj8ljxlxln77vvkxhxssvvb-php-exif-8.2.23/lib/php/extensions/exif.so
extension=/nix/store/m2gs3bdvs7yi73di2ynby65lfyw5f28z-php-fileinfo-8.2.23/lib/php/extensions/fileinfo.so
extension=/nix/store/ych28rny6cv9xx2xxnswgnchjrsnn0vi-php-filter-8.2.23/lib/php/extensions/filter.so
extension=/nix/store/5hggiwr6nx9c6ry7xdva5dhas0g3sf0d-php-ftp-8.2.23/lib/php/extensions/ftp.so
extension=/nix/store/nrlac3kg3x4jrh23zbl1bx39g7piq0g1-php-gd-8.2.23/lib/php/extensions/gd.so
extension=/nix/store/4i8813yp17z3wg7p4c3kp96zjmpndyvk-php-gettext-8.2.23/lib/php/extensions/gettext.so
extension=/nix/store/9kgc27hypqg5586iixhblrhqmchcllm0-php-gmp-8.2.23/lib/php/extensions/gmp.so
extension=/nix/store/qpmv8i01d3f49bsz6xdq7w4gyiwvic3x-php-iconv-8.2.23/lib/php/extensions/iconv.so
extension=/nix/store/dwz1k3qa62nrfx1d9x5c64qwvfdw7dzl-php-imap-8.2.23/lib/php/extensions/imap.so
extension=/nix/store/ql03pjanr9ackxp6ng6j9x7dhiym5s9y-php-intl-8.2.23/lib/php/extensions/intl.so
extension=/nix/store/3091kmp9cdfq7srpi916j7rqz8ldman7-php-ldap-8.2.23/lib/php/extensions/ldap.so
extension=/nix/store/zm63j82y837b4cdlfql1lrcwshbwk1va-php-mbstring-8.2.23/lib/php/extensions/mbstring.so
extension=/nix/store/7jdfrrw4s7w6znghgipz0vq8jck09034-php-mysqlnd-8.2.23/lib/php/extensions/mysqlnd.so
extension=/nix/store/pmnd2l9fjjy0a2vaa8k5idl5qdpaqmac-php-mysqli-8.2.23/lib/php/extensions/mysqli.so
zend_extension=/nix/store/5ddb9655g0fmsbaz64ggs5y2r4db8ab4-php-opcache-8.2.23/lib/php/extensions/opcache.so
extension=/nix/store/f7ax6fwccfzl8chk71y1q5jnm26rq9k8-php-openssl-8.2.23/lib/php/extensions/openssl.so
extension=/nix/store/ny6n1kmx8y6ymbfks5ahp2m8sdjlq311-php-pcntl-8.2.23/lib/php/extensions/pcntl.so
extension=/nix/store/96ldvbhxpykjls6g8ix07a82l5nz1l1p-php-pdo-8.2.23/lib/php/extensions/pdo.so
extension=/nix/store/z6dhzxj784fjsdjijm14j0q3q9f6n6vz-php-pdo_mysql-8.2.23/lib/php/extensions/pdo_mysql.so
extension=/nix/store/4bwzkqhfk006jh2a8b76lr4s2l4mmlhq-php-pdo_odbc-8.2.23/lib/php/extensions/pdo_odbc.so
extension=/nix/store/x4nw63w08a8fx65vg0knsm50np37kdss-php-pdo_pgsql-8.2.23/lib/php/extensions/pdo_pgsql.so
extension=/nix/store/4yyn7bkksdfnzv5njkhz38a1fwygsvjg-php-pdo_sqlite-8.2.23/lib/php/extensions/pdo_sqlite.so
extension=/nix/store/lryrijy2mdyga2hr6wmyzmq97rkgyj02-php-pgsql-8.2.23/lib/php/extensions/pgsql.so
extension=/nix/store/jsbifjpq9kr5sq11nix3lhwidx90jz29-php-posix-8.2.23/lib/php/extensions/posix.so
extension=/nix/store/aa1jq8az0pcl3n0yhz2pyffqbvi8c3b3-php-readline-8.2.23/lib/php/extensions/readline.so
extension=/nix/store/qr3zwib7iz6h779wjakdmc44raw6amyq-php-session-8.2.23/lib/php/extensions/session.so
extension=/nix/store/9py8r6mhrgprnqd4xbqv3w2c7mg30gqv-php-simplexml-8.2.23/lib/php/extensions/simplexml.so
extension=/nix/store/86yw970d01g7a8l2aq28j89vnwkvpkw8-php-sockets-8.2.23/lib/php/extensions/sockets.so
extension=/nix/store/z6njwiyvj7r95y84rkigczjh560c57aw-php-soap-8.2.23/lib/php/extensions/soap.so
extension=/nix/store/bywlhvyx67nhs8gx65j58ff3i24gawli-php-sodium-8.2.23/lib/php/extensions/sodium.so
extension=/nix/store/xhdpnj4yxmgafx1ykylbagrah4pb7bag-php-sysvsem-8.2.23/lib/php/extensions/sysvsem.so
extension=/nix/store/rlir5xm0bsazzmf3j3h0b5p6rlb6avg0-php-sqlite3-8.2.23/lib/php/extensions/sqlite3.so
extension=/nix/store/w8vb3lvr8qhgl7v89plh6nhncfdfrbfm-php-tokenizer-8.2.23/lib/php/extensions/tokenizer.so
extension=/nix/store/ddr2qb6wd7i68pqmyl2m4ikbzzcdz2vb-php-xmlreader-8.2.23/lib/php/extensions/xmlreader.so
extension=/nix/store/sq2vx4slh3rz0623lgdfwrpkypax1kkh-php-xmlwriter-8.2.23/lib/php/extensions/xmlwriter.so
extension=/nix/store/nf8616a70ydcxbbzpn19sgpy19r4hl3l-php-zip-8.2.23/lib/php/extensions/zip.so
extension=/nix/store/8hsg0b8dydmpw3xrp2sgxyg7nxf2kjzy-php-zlib-8.2.23/lib/php/extensions/zlib.so


; MongoDB extension (added by InventoryPro)
extension=/nix/store/28awk63shjqzi2hzlk1qfyachq08jk34-php-mongodb-2.0.0/lib/php/extensions/mongodb.so
